-- Deprecated: mojibake version kept only to avoid silent overwrite. Use 05_add_countries_name_ar.sql instead.
START TRANSACTION;

SET @has_name_ar := (
  SELECT COUNT(*)
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = DATABASE()
    AND TABLE_NAME = 'countries'
    AND COLUMN_NAME = 'name_ar'
);

SET @ddl := IF(
  @has_name_ar = 0,
  'ALTER TABLE countries ADD COLUMN name_ar VARCHAR(120) NULL AFTER name_fr',
  'SELECT ''countries.name_ar already exists'' AS info'
);

PREPARE stmt FROM @ddl;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

UPDATE countries
SET name_ar = CASE alpha2
  WHEN 'AF' THEN 'أفغانستان'
  WHEN 'AL' THEN 'ألبانيا'
  WHEN 'AQ' THEN 'أنتاركتيكا'
  WHEN 'DZ' THEN 'الجزائر'
  WHEN 'AS' THEN 'ساموا الأمريكية'
  WHEN 'AD' THEN 'أندورا'
  WHEN 'AO' THEN 'أنغولا'
  WHEN 'AG' THEN 'أنتيغوا وبربودا'
  WHEN 'AZ' THEN 'أذربيجان'
  WHEN 'AR' THEN 'الأرجنتين'
  WHEN 'AU' THEN 'أستراليا'
  WHEN 'AT' THEN 'النمسا'
  WHEN 'BS' THEN 'جزر البهاما'
  WHEN 'BH' THEN 'البحرين'
  WHEN 'BD' THEN 'بنغلاديش'
  WHEN 'AM' THEN 'أرمينيا'
  WHEN 'BB' THEN 'بربادوس'
  WHEN 'BE' THEN 'بلجيكا'
  WHEN 'BM' THEN 'برمودا'
  WHEN 'BT' THEN 'بوتان'
  WHEN 'BO' THEN 'بوليفيا'
  WHEN 'BA' THEN 'البوسنة والهرسك'
  WHEN 'BW' THEN 'بوتسوانا'
  WHEN 'BV' THEN 'جزيرة بوفيه'
  WHEN 'BR' THEN 'البرازيل'
  WHEN 'BZ' THEN 'بليز'
  WHEN 'IO' THEN 'الإقليم البريطاني في المحيط الهندي'
  WHEN 'SB' THEN 'جزر سليمان'
  WHEN 'VG' THEN 'جزر فيرجن البريطانية'
  WHEN 'BN' THEN 'بروناي'
  WHEN 'BG' THEN 'بلغاريا'
  WHEN 'MM' THEN 'ميانمار (بورما)'
  WHEN 'BI' THEN 'بوروندي'
  WHEN 'BY' THEN 'بيلاروس'
  WHEN 'KH' THEN 'كمبوديا'
  WHEN 'CM' THEN 'الكاميرون'
  WHEN 'CA' THEN 'كندا'
  WHEN 'CV' THEN 'الرأس الأخضر'
  WHEN 'KY' THEN 'جزر كايمان'
  WHEN 'CF' THEN 'جمهورية أفريقيا الوسطى'
  WHEN 'LK' THEN 'سريلانكا'
  WHEN 'TD' THEN 'تشاد'
  WHEN 'CL' THEN 'تشيلي'
  WHEN 'CN' THEN 'الصين'
  WHEN 'TW' THEN 'تايوان'
  WHEN 'CX' THEN 'جزيرة كريسماس'
  WHEN 'CC' THEN 'جزر كوكوس (كيلينغ)'
  WHEN 'CO' THEN 'كولومبيا'
  WHEN 'KM' THEN 'جزر القمر'
  WHEN 'YT' THEN 'مايوت'
  WHEN 'CG' THEN 'جمهورية الكونغو'
  WHEN 'CD' THEN 'جمهورية الكونغو الديمقراطية'
  WHEN 'CK' THEN 'جزر كوك'
  WHEN 'CR' THEN 'كوستاريكا'
  WHEN 'HR' THEN 'كرواتيا'
  WHEN 'CU' THEN 'كوبا'
  WHEN 'CY' THEN 'قبرص'
  WHEN 'CZ' THEN 'التشيك'
  WHEN 'BJ' THEN 'بنين'
  WHEN 'DK' THEN 'الدانمرك'
  WHEN 'DM' THEN 'دومينيكا'
  WHEN 'DO' THEN 'جمهورية الدومينيكان'
  WHEN 'EC' THEN 'الإكوادور'
  WHEN 'SV' THEN 'السلفادور'
  WHEN 'GQ' THEN 'غينيا الاستوائية'
  WHEN 'ET' THEN 'إثيوبيا'
  WHEN 'ER' THEN 'إريتريا'
  WHEN 'EE' THEN 'إستونيا'
  WHEN 'FO' THEN 'جزر فارو'
  WHEN 'FK' THEN 'جزر فوكلاند'
  WHEN 'GS' THEN 'جورجيا الجنوبية وجزر ساندويتش الجنوبية'
  WHEN 'FJ' THEN 'فيجي'
  WHEN 'FI' THEN 'فنلندا'
  WHEN 'AX' THEN 'جزر آلاند'
  WHEN 'FR' THEN 'فرنسا'
  WHEN 'GF' THEN 'غويانا الفرنسية'
  WHEN 'PF' THEN 'بولينيزيا الفرنسية'
  WHEN 'TF' THEN 'الأقاليم الجنوبية الفرنسية'
  WHEN 'DJ' THEN 'جيبوتي'
  WHEN 'GA' THEN 'الغابون'
  WHEN 'GE' THEN 'جورجيا'
  WHEN 'GM' THEN 'غامبيا'
  WHEN 'PS' THEN 'فلسطين'
  WHEN 'DE' THEN 'ألمانيا'
  WHEN 'GH' THEN 'غانا'
  WHEN 'GI' THEN 'جبل طارق'
  WHEN 'KI' THEN 'كيريباتي'
  WHEN 'GR' THEN 'اليونان'
  WHEN 'GL' THEN 'غرينلاند'
  WHEN 'GD' THEN 'غرينادا'
  WHEN 'GP' THEN 'غوادلوب'
  WHEN 'GU' THEN 'غوام'
  WHEN 'GT' THEN 'غواتيمالا'
  WHEN 'GN' THEN 'غينيا'
  WHEN 'GY' THEN 'غيانا'
  WHEN 'HT' THEN 'هايتي'
  WHEN 'HM' THEN 'جزيرة هيرد وجزر ماكدونالد'
  WHEN 'VA' THEN 'دولة الفاتيكان'
  WHEN 'HN' THEN 'هندوراس'
  WHEN 'HK' THEN 'هونغ كونغ'
  WHEN 'HU' THEN 'هنغاريا'
  WHEN 'IS' THEN 'آيسلندا'
  WHEN 'IN' THEN 'الهند'
  WHEN 'ID' THEN 'إندونيسيا'
  WHEN 'IR' THEN 'إيران'
  WHEN 'IQ' THEN 'العراق'
  WHEN 'IE' THEN 'أيرلندا'
  WHEN 'IL' THEN 'إسرائيل'
  WHEN 'IT' THEN 'إيطاليا'
  WHEN 'CI' THEN 'ساحل العاج'
  WHEN 'JM' THEN 'جامايكا'
  WHEN 'JP' THEN 'اليابان'
  WHEN 'KZ' THEN 'كازاخستان'
  WHEN 'JO' THEN 'الأردن'
  WHEN 'KE' THEN 'كينيا'
  WHEN 'KP' THEN 'كوريا الشمالية'
  WHEN 'KR' THEN 'كوريا الجنوبية'
  WHEN 'KW' THEN 'الكويت'
  WHEN 'KG' THEN 'قيرغيزستان'
  WHEN 'LA' THEN 'لاوس'
  WHEN 'LB' THEN 'لبنان'
  WHEN 'LS' THEN 'ليسوتو'
  WHEN 'LV' THEN 'لاتفيا'
  WHEN 'LR' THEN 'ليبيريا'
  WHEN 'LY' THEN 'ليبيا'
  WHEN 'LI' THEN 'ليختنشتاين'
  WHEN 'LT' THEN 'ليتوانيا'
  WHEN 'LU' THEN 'لوكسمبورغ'
  WHEN 'MO' THEN 'ماكاو'
  WHEN 'MG' THEN 'مدغشقر'
  WHEN 'MW' THEN 'ملاوي'
  WHEN 'MY' THEN 'ماليزيا'
  WHEN 'MV' THEN 'جزر المالديف'
  WHEN 'ML' THEN 'مالي'
  WHEN 'MT' THEN 'مالطا'
  WHEN 'MQ' THEN 'جزر المارتينيك'
  WHEN 'MR' THEN 'موريتانيا'
  WHEN 'MU' THEN 'موريشيوس'
  WHEN 'MX' THEN 'المكسيك'
  WHEN 'MC' THEN 'موناكو'
  WHEN 'MN' THEN 'منغوليا'
  WHEN 'MD' THEN 'مولدوفا'
  WHEN 'MS' THEN 'مونتسرات'
  WHEN 'MA' THEN 'المغرب'
  WHEN 'MZ' THEN 'موزمبيق'
  WHEN 'OM' THEN 'عُمان'
  WHEN 'NA' THEN 'ناميبيا'
  WHEN 'NR' THEN 'ناورو'
  WHEN 'NP' THEN 'نيبال'
  WHEN 'NL' THEN 'هولندا'
  WHEN 'AN' THEN 'جزر الأنتيل الهولندية'
  WHEN 'AW' THEN 'أروبا'
  WHEN 'NC' THEN 'كاليدونيا الجديدة'
  WHEN 'VU' THEN 'فانواتو'
  WHEN 'NZ' THEN 'نيوزيلندا'
  WHEN 'NI' THEN 'نيكاراغوا'
  WHEN 'NE' THEN 'النيجر'
  WHEN 'NG' THEN 'نيجيريا'
  WHEN 'NU' THEN 'نيوي'
  WHEN 'NF' THEN 'جزيرة نورفولك'
  WHEN 'NO' THEN 'النرويج'
  WHEN 'MP' THEN 'جزر ماريانا الشمالية'
  WHEN 'UM' THEN 'جزر الولايات المتحدة النائية'
  WHEN 'FM' THEN 'ميكرونيزيا'
  WHEN 'MH' THEN 'جزر مارشال'
  WHEN 'PW' THEN 'بالاو'
  WHEN 'PK' THEN 'باكستان'
  WHEN 'PA' THEN 'بنما'
  WHEN 'PG' THEN 'بابوا غينيا الجديدة'
  WHEN 'PY' THEN 'باراغواي'
  WHEN 'PE' THEN 'بيرو'
  WHEN 'PH' THEN 'الفلبين'
  WHEN 'PN' THEN 'جزر بيتكيرن'
  WHEN 'PL' THEN 'بولندا'
  WHEN 'PT' THEN 'البرتغال'
  WHEN 'GW' THEN 'غينيا بيساو'
  WHEN 'TL' THEN 'تيمور - ليشتي'
  WHEN 'PR' THEN 'بورتوريكو'
  WHEN 'QA' THEN 'قطر'
  WHEN 'RE' THEN 'روينيون'
  WHEN 'RO' THEN 'رومانيا'
  WHEN 'RU' THEN 'روسيا'
  WHEN 'RW' THEN 'رواندا'
  WHEN 'SH' THEN 'سانت هيلينا'
  WHEN 'KN' THEN 'سانت كيتس ونيفيس'
  WHEN 'AI' THEN 'أنغويلا'
  WHEN 'LC' THEN 'سانت لوسيا'
  WHEN 'PM' THEN 'سان بيير ومكويلون'
  WHEN 'VC' THEN 'سانت فنسنت وجزر غرينادين'
  WHEN 'SM' THEN 'سان مارينو'
  WHEN 'ST' THEN 'ساو تومي وبرينسيبي'
  WHEN 'SA' THEN 'المملكة العربية السعودية'
  WHEN 'SN' THEN 'السنغال'
  WHEN 'SC' THEN 'سيشل'
  WHEN 'SL' THEN 'سيراليون'
  WHEN 'SG' THEN 'سنغافورة'
  WHEN 'SK' THEN 'سلوفاكيا'
  WHEN 'VN' THEN 'فيتنام'
  WHEN 'SI' THEN 'سلوفينيا'
  WHEN 'SO' THEN 'الصومال'
  WHEN 'ZA' THEN 'جنوب أفريقيا'
  WHEN 'ZW' THEN 'زيمبابوي'
  WHEN 'ES' THEN 'إسبانيا'
  WHEN 'EH' THEN 'الصحراء الغربية'
  WHEN 'SD' THEN 'السودان'
  WHEN 'SR' THEN 'سورينام'
  WHEN 'SJ' THEN 'سفالبارد وجان ماين'
  WHEN 'SZ' THEN 'إسواتيني'
  WHEN 'SE' THEN 'السويد'
  WHEN 'CH' THEN 'سويسرا'
  WHEN 'SY' THEN 'سوريا'
  WHEN 'TJ' THEN 'طاجيكستان'
  WHEN 'TH' THEN 'تايلاند'
  WHEN 'TG' THEN 'توغو'
  WHEN 'TK' THEN 'توكيلاو'
  WHEN 'TO' THEN 'تونغا'
  WHEN 'TT' THEN 'ترينيداد وتوباغو'
  WHEN 'AE' THEN 'الإمارات العربية المتحدة'
  WHEN 'TN' THEN 'تونس'
  WHEN 'TR' THEN 'تركيا'
  WHEN 'TM' THEN 'تركمانستان'
  WHEN 'TC' THEN 'جزر توركس وكايكوس'
  WHEN 'TV' THEN 'توفالو'
  WHEN 'UG' THEN 'أوغندا'
  WHEN 'UA' THEN 'أوكرانيا'
  WHEN 'MK' THEN 'مقدونيا الشمالية'
  WHEN 'EG' THEN 'مصر'
  WHEN 'GB' THEN 'المملكة المتحدة'
  WHEN 'IM' THEN 'جزيرة مان'
  WHEN 'TZ' THEN 'تنزانيا'
  WHEN 'US' THEN 'الولايات المتحدة'
  WHEN 'VI' THEN 'جزر فيرجن الأمريكية'
  WHEN 'BF' THEN 'بوركينا فاسو'
  WHEN 'UY' THEN 'أورغواي'
  WHEN 'UZ' THEN 'أوزبكستان'
  WHEN 'VE' THEN 'فنزويلا'
  WHEN 'WF' THEN 'جزر والس وفوتونا'
  WHEN 'WS' THEN 'ساموا'
  WHEN 'YE' THEN 'اليمن'
  WHEN 'CS' THEN 'صربيا والجبل الأسود'
  WHEN 'ZM' THEN 'زامبيا'
  ELSE name_ar
END;

COMMIT;
